### ISSUE TITLE
Mention your Contributions on my talk

### ISSUE THREAD

**Issue by ivanpaulovich** [ivanpaulovich/clean-architecture-manga#100]
Hi folks,

I'd like to inform that I will mention your contributions on my [Clean Architecture Essentials talk](https://www.meetup.com/Stockholm-Software-Craftsmanship/events/265811317/).

Thank you so much for the ideas, pull requests and issues.

![clean-architecture-essentials-meetup-references png](https://user-images.githubusercontent.com/7133698/68468333-1996b800-0218-11ea-9f36-c7d479dbf3c5.jpg)

I will update you after the meetup 🍺

**Comment by phmatray** [comment]
I'm a little far from Stockholm, but I wish you good luck tonight. :)

**Comment by ivanpaulovich** [comment]
Thanks @phmatray :)
This talk explains why I am few last days away from GitHub. I will be back soon with the recording and the walkthrough article on our project.

**Comment by ivanpaulovich** [comment]
Hey all,

I finally published an article on dev.to (my first one) with a walkthrough our project and the meetup recording that I mentioned before.

[Clean Architecture Essentials - Sthlm Software Craftsmanship Meetup](https://dev.to/ivanpaulovich/clean-architecture-essentials-5a0m)
