### ISSUE TITLE
A use case to request a list of items

### ISSUE THREAD

**Issue by leandrofagundes** [ivanpaulovich/clean-architecture-manga#105]
Hi guys,

we can see here how to implement must of the time a one-to-one needed.
If you need a customer, you got it. If you need a account, you got it.
But if I want to do a report with all my customers, showing the total balance for each one, how it should work? 

I'm afraid about how the relation between each customer will be with his many accounts.

ps: Sorry if I'm making this wrong, it's my first time participating on github.

**Comment by ivanpaulovich** [comment]
Hi @leandrofagundes,

We could design a `Query stack` in which the `GetAllCustomersAccountsUseCase` is completely implemented within the Infrastructure layer. 

To achieve this, we still need:

* The Input/Output ports are designed in the Application layer.
* The `GetAllCustomersAccountsUseCase` is implemented in the Infrastructure layer.

Benefits of this is that we do not change the Domain to support these specifics queries, instead we could use Raw Queries that return the expected output model.

**Comment by leandrofagundes** [comment]
Thanks for your answer, @ivanpaulovich !

So, you mean the Infrastructure layer should have a method exclusive for this?
I was thinking about the Entity Framework, first. You ask for the EF customers with accounts and It will bring the related stuff.

So, my Interface of Customers Repository should have a Get, Add, Update, Delete and now a GetAllCustomersAccountsUseCase for this case? I thought it will be something much more related to the Use Case. Ins't it bring to the infrastructure layer a rule?

**Comment by ivanpaulovich** [comment]
Hey @leandrofagundes,

The motivation behind implementing the queries completely on the Infrastructure Layer is to minimize the conversions between objects. Make the architecture slim for queries and avoid the constraints of the Domain Layer.

You may had noticed in Manga that the repositories always return Entities, then the UseCases return OutputMessages. If you implement complex queries in the Infrastructure layer and they return OutputMessages so you can avoid these conversions.

Keep in mind that these Queries should not be used inside the application, the queries consumer should be the user interface.

**Comment by leandrofagundes** [comment]
Thanks, I'll try to open my mind. It's an exercise to change the old and wrong way for me, but I'll do my best hehe.
