### ISSUE TITLE
Automatic implementation of GetHashcode and Equals in structs.

### ISSUE THREAD

**Issue by phmatray** [ivanpaulovich/clean-architecture-manga#107]
I think I just learned something...
So, do we really need to implement IEquatable for value objects?

https://stackoverflow.com/a/32797530/2409554

**Comment by ivanpaulovich** [comment]
Hi @phmatray,

The motivation to implement IEquatable was to allow Dictionary, Collections of Value Objects. 

https://docs.microsoft.com/en-us/dotnet/api/system.iequatable-1?view=netframework-4.8

> The IEquatable<T> interface is used by generic collection objects such as Dictionary<TKey,TValue>, List<T>, and LinkedList<T> when testing for equality in such methods as Contains, IndexOf, LastIndexOf, and Remove. It should be implemented for any object that might be stored in a generic collection.

Did you try removing the interface?

**Comment by phmatray** [comment]
Hi @ivanpaulovich
I've found Donald Duck with an equality check in a collection without implementing IEquatable.

> A pretty cool, not so well known advantage of Structs over Classes is that there is an automatic implementation of GetHashcode and Equals in structs.
That's pretty useful when keys are required for dictionaries

How could I go any further in these tests?
For the moment, this seems to confirm that IEquatable is not required.

```csharp
    class Program
    {
        static void Main(string[] args)
        {
            var userCollection = new[]
            {
                new Person("Mickey", "Mouse"),
                new Person("Minnie", "Mouse"),
                new Person("Donald", "Duck") 
            };

            var anotherUserWithSameProps = new Person("Donald", "Duck");

            Console.WriteLine("Equality check");
            foreach (var person in userCollection)
            {
                string output = person.Equals(anotherUserWithSameProps)
                    ? $"FOUND - {person}"
                    : person.ToString();
                
                Console.WriteLine(output);
            }
        }
    }

    struct Person
    {
        private readonly string _firstName;
        private readonly string _lastName;

        public Person(string firstName, string lastName)
        {
            _firstName = firstName;
            _lastName = lastName;
        }

        public override string ToString()
            => $"{_firstName} {_lastName}";
    }
```

**Comment by ivanpaulovich** [comment]
> How could I go any further in these tests?

After we remove the `IEquatable` interface and their related implementation, if tests are green we merge straight way.

**Comment by phmatray** [comment]
I just downloaded a copy of the repository and made these changes. The tests remain green. 

![tests](https://user-images.githubusercontent.com/9035444/69060194-410b3300-0a17-11ea-90b5-a904703a7e29.png)

**Comment by ivanpaulovich** [comment]
Let’s merge it ASAP.
@phmatray I invited you before, do you wanna be part of the project contributors?

**Comment by phmatray** [comment]
> @phmatray I invited you before, do you wanna be part of the project contributors?
Yes, of course :)

**Comment by ivanpaulovich** [comment]
> > @phmatray I invited you before, do you wanna be part of the project contributors?
> 
> Yes, of course 😄

I sent the invite
