### ISSUE TITLE
Isn't the presenters of InDatabaseMemory a responsability of the Test Project?

### ISSUE THREAD

**Issue by leandrofagundes** [ivanpaulovich/clean-architecture-manga#114]
As I can see, the UnitTests needs a presenter to test, and because of this, a Presenter was created on the Infrastructure layer.

Ins't this presenter a complet UnitTest responsability like the presenter of the api is?

**Comment by ivanpaulovich** [comment]
Hey @leandrofagundes,

There are several strategies to test, I try to follow the [Martin Fowler Testing guide](https://martinfowler.com/articles/microservice-testing/).

The UnitTests are targeting the UseCases and are tested quite extensively, the other classes are collaborators (Mocks, Fakes and Stubs) that are just used.

You can test the Presenters, but if so write tests against the Real Presenters in the WebApi layer.

**Comment by leandrofagundes** [comment]
@ivanpaulovich so, what are the Presenters inside the Infrastructure project for?

Infrastructure\InMemoryDataAccess\Presenters

Shouldn't those presenters be at Test project?

**Comment by ivanpaulovich** [comment]
Hey! Those presenters are Fakes and are used only by the Unit Tests (at this moment).

Have you noticed that the application runs differently in Development and in Production environments?

On my opinion the application can run with Fakes, the same way we use in memory persistence for development we could use “in memory presenters output”.

And this is were Unit Tests and Fakes starts to pay off because they can run in production.

**Comment by leandrofagundes** [comment]
Yeah @ivanpaulovich I got it but the question is about the place we put the presenters.

I changed here the presenters to the Test project, so, it'll be used only duringt tests. Make sense to me, but I want to know if it's more related to the infrastructure layer (inside indbmemory folder) or it could be inside the tests project.

**Comment by ivanpaulovich** [comment]
Hey @leandrofagundes,

Let's be pragramatic, keep them where is more clear and useful for you. The Manga project shows many techniques that you may or may not use.

**Comment by leandrofagundes** [comment]
Thanks, I'll keep on the tests project. If you think for any real reason to keep in the infra layer, let me know!
