### ISSUE TITLE
Understanding more about patterns, please?

### ISSUE THREAD

**Issue by leandrofagundes** [ivanpaulovich/clean-architecture-manga#118]
I'm trying to figure out how the following problem should be solved:

I have a Bank entity.
Users of the system could be customer, manager, director or just a bank operator.
All of them will be a customer too, because to work on a bank, you should have an account.

So, should all of them implements ICustomer?
Should I have IManager which implements ICustomer? (always expanding my class, never changing it as OCP said).

Thanks guys

**Comment by ivanpaulovich** [comment]
Hey @leandrofagundes, considering the information you provided it is right. But I would need more input to design something like that correctly.

**Comment by leandrofagundes** [comment]
I guess it's much more about when the customer is using the system, no matter (during a use case for Customer) if he is a manager or anything else.

He will need to generate the loan, open a new window (for a new use case, now as a manager) and execute the loan approval.

Probably there is another interface needed, like a person (under customer and manager), and not the manager implementing customer directly.

Just trying to create situations. I'll try to take time and courage to open a change with something like that and send to you a PR, so you can validate the idea. Courage, first!
