### ISSUE TITLE
ValueObjects and DomainExceptions - centralized or decentralized

### ISSUE THREAD

**Issue by bommen** [ivanpaulovich/clean-architecture-manga#121]
I noticed that the ValueObjects and DomainExceptions are placed in a cental folder ValueObjects. In another issue (#115) a statement was made that ValueObjects should be tied to one specific entity. Is there a case to be made to place ValueObejcts in the same namespace as their respective Entity?
When a project grows I could imagine this would make them easier to find.

**Comment by ivanpaulovich** [comment]
Hey @bommen,

You are totally right!
The Value Objects are specific to the Entities, let's move the VO closer to them.

**Comment by ivanpaulovich** [comment]
Hey @bommen,  I appreciate your input.
Could I add your GitHub handle to the contributors list?

**Comment by bommen** [comment]
The whole concept of Clean Architecture fascinates me enormously, and this seems a really nice project to get the hang of it. If by contributing I can help give the project more body I would really like thay!

**Comment by ivanpaulovich** [comment]
I sent you a GitHub invite to join the collaborators. Bring on the ideas and code! 
@all-contributors please add @bommen for ideas.

**Comment by ivanpaulovich** [comment]
The last PRs segregated the Value Objects per Bounded Context. Closing for now.
