### ISSUE TITLE
Shouldn't entities be Abstract? 

### ISSUE THREAD

**Issue by leandrofagundes** [ivanpaulovich/clean-architecture-manga#123]
As I noticed, entities shouldn't be created anytime, only by the factory. The only part of an entity that should be created is the entities of the infrastructure layers.

Based on this, why entities aren't abstract?

**Comment by ivanpaulovich** [comment]
Hey @leandrofagundes,

Yes, Entities should be abstract but I tried doing that and I had issues with Entity Framework.
Pease share your findings if you could achieve that.

**Comment by leandrofagundes** [comment]
Ok, I'll keep it open until I reach that point!
I'm still changing folders and namespaces every day trying to find something that makes sense :(

**Comment by ivanpaulovich** [comment]
@leandrofagundes entities were changed to abstract on https://github.com/ivanpaulovich/clean-architecture-manga/pull/131

**Comment by leandrofagundes** [comment]
Amazing @ivanpaulovich! I was working on it (even with entities as interfaces) and was doing well, but last week was on vacation and didn't get on my laptop!
I'll check your solution!

**Comment by leandrofagundes** [comment]
Hey @ivanpaulovich, and if we want to use identity? How the entities from the infrastructure layer will implement IdentityUser and my entity at the same time?
Should those entities be only on infrastructure layer?

**Comment by ivanpaulovich** [comment]
Hey @leandrofagundes,

I am not aware of this specifics. Could you share some code?

**Comment by ivanpaulovich** [comment]
Closing the thread. Feel free to open a new issue.
