### ISSUE TITLE
Please remove IAccount from Customers Bounded Context

### ISSUE THREAD

**Issue by ivanpaulovich** [ivanpaulovich/clean-architecture-manga#130]
In order to decouple Customers and Account, both aggregate should only see each other through their IDs. Please remove IAccount from Customers:

https://github.com/ivanpaulovich/clean-architecture-manga/blob/master/src/Domain/Customers/Customer.cs#L21

**Comment by bommen** [comment]
Agreed. However, this would still mean that ICustomer would still reference AccountId, which is part of the Account Boundex Context.

**Comment by ivanpaulovich** [comment]
I think `AccountId` value object should be duplicated. One for Customer BC and another for Accounts BC.

**Comment by bommen** [comment]
Wouldn't this make the system vulnerable to changes? If the AccountId in the Accounts BC changes (starts using `int` instead of `Guid`), the Customer BC would need to change also.

**Comment by bommen** [comment]
I see three scenarios in this case:

1. Use `IAccount `in Customers: References Aggregate Root of Accounts Aggregate, would comply to DDD principles, but probably exposes too much of the internal workings of `IAccount`.
2. Reference `AccountId `(new ValueObject in `Domain.Customers.ValueObjects`): Only references the Identity of `IAccount`. Needs integration test to ensure that `Domain.Accounts.ValueObjects.AccountId` has the same structure as `Domain.Customers.ValueObjects.AccountId`
3. Use `Guid `- Not preferrable as it makes an assumption about the implementation detail of `IAccount`.

In spite of my earlier comment my preference would go out to option 2.

**Comment by ivanpaulovich** [comment]
Hey @bommen,

Interesting input, let's keep the shared `AccountId`, `CustomerId` and `UserId` value objects for a while.

I'd like to achieve a loose-coupling between these modules, a kind of [Shared Kernel](https://medium.com/ingeniouslysimple/context-mapping-in-domain-driven-design-9063465d2eb8)?

The relationship of Security to Customers will be conformist.

The working in progress is here https://github.com/ivanpaulovich/clean-architecture-manga/pull/131/files
