### ISSUE TITLE
Instead of DI in the controllers constructors use [FromServices] DI

### ISSUE THREAD

**Issue by ivanpaulovich** [ivanpaulovich/clean-architecture-manga#132]
We could injection the IMediator and Presenter through the [FromServices]. Like it is done at: https://docs.microsoft.com/en-us/aspnet/core/mvc/controllers/dependency-injection?view=aspnetcore-3.1#action-injection-with-fromservices

**Comment by qpippop** [comment]
In my view, you need to restructure the project to reuse controllers between UseCases (this way [FromServices] will be useful).

**Comment by ivanpaulovich** [comment]
Hey @qpippop,

I like the separation by use cases and I am still thinking about your suggestion.

**Comment by ivanpaulovich** [comment]
@qpippop can I add your GitHub to the contributors page?

**Comment by qpippop** [comment]
@ivanpaulovich of course, I like your projects and I'm glad to help!

**Comment by ivanpaulovich** [comment]
@all-contributors please add @qpippop for ideas.

**Comment by ivanpaulovich** [comment]
[FromServices] added to the latest changes. It's up to developer to decide to use the constructor injection.

**Comment by maikmb** [comment]
Hi Ivan! What are the positive aspects of using [FomServices] DI?

Em sáb., 23 de mai. de 2020 às 09:09, Ivan Paulovich <
notifications@github.com> escreveu:

**Comment by ivanpaulovich** [comment]
Hi @maikmb,

I am not sure about the ASP NET internals when using [FromServices], I guess it gives us the same functionality but it saves us a few lines from the classic constructor injection pattern.
