### ISSUE TITLE
CQRS / Event Sourcing support

### ISSUE THREAD

**Issue by bommen** [ivanpaulovich/clean-architecture-manga#136]
In order to fully harness the benefits of Domain Driven Design a CQRS / Event Sourcing implementation would be awesome. How would you approach this?

**Comment by ivanpaulovich** [comment]
Interesting question @bommen, we could move the project into the Aggregates/ES direction.

I have a old [Aggregates/ES sample implementation](https://github.com/ivanpaulovich/event-sourcing-castanha/blob/master/source/WebAPI/Castanha.Domain/Accounts/Account.cs) that will inspire changes on Manga project.

I see the journey to Aggregates/ES as the following stages:

1. Anemic Domain.
2. Rich Domain with Behaviors.
3. Design small Aggregates.
4. Start publishing events for Audit purpose.
  * Design Events
  * Publish Events
5. Reconstruct Aggregate state from Events.

We just finished the **Design small Aggregates stage** on Manga project, the next step is to choose one Aggregate (eg. Accounts Aggregate), design their events and start publishing it.

Design events like this on the Accounts Bounded Context:

* OpenedDomainEvent
* DepositedDomainEvent
* WithdrewDomainEvent
* ClosedDomainEvent

Raise these events and make the aggregate expose an "EventsCollection" property, from there we publish the events to Kafka or NSB.
