### ISSUE TITLE
Please support Prometheus metrics

### ISSUE THREAD

**Issue by ivanpaulovich** [ivanpaulovich/clean-architecture-manga#137]
It would be nice to add `/metrics` endpoint with Prometheus metrics, following [Reporting Metrics To Prometheus In ASP.NET Core](https://www.c-sharpcorner.com/article/reporting-metrics-to-prometheus-in-asp-net-core/) is straightforward.

**Comment by cesinhaugusto** [comment]
Paulo, I'd like to tackle this issue.

**Comment by ivanpaulovich** [comment]
Bring it on @cesinhaugusto 😎
