### ISSUE TITLE
.NET Core version conflict

### ISSUE THREAD

**Issue by cesinhaugusto** [ivanpaulovich/clean-architecture-manga#140]
Although it is described on the project's main page that we're using .NET Core 3.1, the global.json file makes reference to 3.0 version. Should the version be upgraded to 3.1?

I'm bringing this issue up because support to 3.0 will end on 2020-03-03, according to Microsoft. I also believe it doesn't impact on the codebase, resulting in only updating the global.json file.

**Comment by ivanpaulovich** [comment]
Good catch! 
It would be nice if you open a PR or include this change in your prometheus PR.
