### ISSUE TITLE
Discussão em Português [pt-br]

### ISSUE THREAD

**Issue by ivanpaulovich** [ivanpaulovich/clean-architecture-manga#149]
Ainda que issues em inglês possam alcançar uma audiência maior e ter mais interaçoes, eu gostaria de encorajar os desenvolvedores em língua portuguesa a usarem este tópico para discussão.

Sejam bem vindos e vocês terão atencão especial.

> Pinned issue for interacting with Brazilian-Portuguese developers community.
> **English Speakers**, please unsubscribe 👀

**Comment by maikmb** [comment]
Gostaria de ajudar no projeto!

**Comment by ivanpaulovich** [comment]
Olá @maikmb,

O que o projeto mais precisa no momento é de uma interface de usuário (React, Blazor, etc). Se tiver interesse nisso seria bem vindo.
No mais, fazendo perguntas já está ajudando bastante.

**Comment by maikmb** [comment]
Eu posso tentar ajudar com uma interface em ReactJs. Seria para realizar as
operações da API?

Em seg, 20 de jan de 2020 09:54, Ivan Paulovich <notifications@github.com>
escreveu:

**Comment by ivanpaulovich** [comment]
Sim e seria muito bem vindo.

Coloquei no azure uma versao da API: https://clean-architecture-manga.azurewebsites.net/swagger/index.html e acho que preciso corrigir a URL de autenticacao que deveria ser https://clean-architecture-manga.azurewebsites.net/login.

**Comment by maikmb** [comment]
Combinado! Vou iniciar uma nova branch para incluirmos o projeto web.

**Comment by leandrofagundes** [comment]
Eu por enquanto fico gerando dúvidas na minha cabeça pra ver se gero uma na tua também hahaha.
@ivanpaulovich, eu não consigo vislumbrar a criação de classes que dependem de várias tabelas nesse modelo. Tipo um relatório e seus filtros. 
1) Todos os filtros devem estar na DTO da Request pro caso de uso? 
2) Digamos que eu vou apresentar uma lista de contas, mas quero mostrar o saldo dela, o nome do cliente e o nome do gerente. Minha busca vai ser no repositório de accounts, mas pra pegar o nome do gerente preciso ir em outro repositório. Em que momento faço essa mescla dos dados?

**Comment by ivanpaulovich** [comment]
Olá @leandrofagundes,

> Todos os filtros devem estar na DTO da Request pro caso de uso?
> Digamos que eu vou apresentar uma lista de contas, mas quero mostrar o saldo dela, o nome do
> cliente e o nome do gerente. Minha busca vai ser no repositório de accounts, mas pra pegar o 
> nome do gerente preciso ir em outro repositório. Em que momento faço essa mescla dos dados?

1. Sim. Filtros na DTO do Request.
1. Você nao precisa reutilizar os repositorios para gerar o relatorio. Ao inves de usar os Repositorios você modela uma interface para consultas:

```cs
public interface IRelatorioContas
{
     Task<RelatorioContasModel> BuscarResumoContas(string nomeGerente, int UF);
}
```

E no seu caso de uso, você injeta `IRelatorioContas`, a implementacao você faz na Infrastruture e acessa diretamente o Context do EF ou SQL crú,

O importante é que o retorno do IRelatorioContas,BuscarResumoContas() vai ser usado pelo caso de uso pra gerar um `RelatorioContasResponse`, sem a necessidade de instanciar Entities e aggregates que por definicao sao altamente consistentes,

**Comment by leandrofagundes** [comment]
Hmm, não conhecia esse tipo de prática. Talvez eu não consiga assimilar uma Model que não representa nada de verdade no banco de dados.
Existe alguma leitura que tu recomenda ou exemplos que deixem isso visualmente mais claro sem quebrar a clean architecture?

Eu to aqui pensando em como vai ser segmentado esse Model que tu citou.

**Comment by ivanpaulovich** [comment]
> Existe alguma leitura que tu recomenda ou exemplos que deixem isso visualmente mais claro sem quebrar a clean architecture?

O padrão [CQRS](https://martinfowler.com/bliki/CQRS.html) tem varios sábores de implementacao, e um deles é a criacao de um Model para Leitura, e um Model para Escrita. No seu caso, eu imagino que o Model de Leitura sao as classes que representam as views do BD.

> O lazy loading do EF não é recomendado?? Pq tu não usa o Linq to Entities pra montar tuas consultas, preferindo o SQL crú?

Isso depende. LazyLoading é quase mágica, não gosto quando magica se infiltra no Application+Domain.

**Comment by rodrigoreis** [comment]
E ai @ivanpaulovich como estão as coisas?

Estou usando esta arquitetura como arquitetura de referência para um cliente, muito obrigado pelo projeto. Aproveito para acrescentar que no nosso desenho estamos utilizando uma estrutura de integração via _gateways_, estes estão sendo tratados como possíveis dependências de serviço, ou seja, o serviço agora quando precisa de uma integração externa injetamos o _gateway_ que implementamos ainda na camada de infra.

O que acha?

Forte abraço.

**Comment by vmamore** [comment]
Fala @rodrigoreis , fiquei curioso para entender o que essa abordagem resolve, porém não entendi muito bem como está a implementação. Poderia explicar melhor ou mostrar o desenho? Valeu!

**Comment by ivanpaulovich** [comment]
> E ai @ivanpaulovich como estão as coisas?
> 
> Estou usando esta arquitetura como arquitetura de referência para um cliente, muito obrigado pelo projeto. Aproveito para acrescentar que no nosso desenho estamos utilizando uma estrutura de integração via _gateways_, estes estão sendo tratados como possíveis dependências de serviço, ou seja, o serviço agora quando precisa de uma integração externa injetamos o _gateway_ que implementamos ainda na camada de infra.
> 
> O que acha?
> 
> Forte abraço.

Olá @rodrigoreis, tirando o frio de lascar está tudo ótimo por aqui :)

Me corrija se eu entendi errado. 

1. Você implementa a comunicação com os Gateways (Web Services, Cloud, HTTP) na camada de infraestrutura?
1. Você injeta a interface desses servicos nos casos de usos?

Sim sim, isso é bem semelhante ao que propomos no Manga. Poderia compartilhar mais detalhes?
Abraço!

**Comment by mviegas** [comment]
Fala Ivan, tudo bem?

Uma dúvida que surgiu aqui enquanto eu lia o código: os UseCases não são parte do domínio da aplicação e, portanto, deveriam estar no layer de domínio e não no de aplicação?

**Comment by ivanpaulovich** [comment]
Hey @mviegas!

- Na camada `Application` eu coloco as regras de negocio concretas e mais especialistas para essa Aplicação (leia o sofftware em si) ou que consomem recursos externos (UnitOfWork faz commit no banco).
- Na camada `Domain` eu implemento os diversos Bounded Contexts e suas Agregacoes, Os domain services fazem operacoes apenas em memoria, e se eu quisesse poderia extrair o Domain e montar uma aplicacao bem diferente (Domain é altamente abstrato).
- Os UseCases acessam multiplos BCs. 

> Uma dúvida que surgiu aqui enquanto eu lia o código: os UseCases não são parte do domínio da aplicação e, portanto, deveriam estar no layer de domínio e não no de aplicação?

O `RegisterUseCase` usa Customer, Account and Security e acho que ficaria dificl dizer em qual BC cada caso de uso deveria ser implementado. Minha solucao foi coloca-los numa camada mais externa que pode acessar qualquer BC.

Esse modelo serve pra mim. Algum exemplo que possa compartilhar?

**Comment by mviegas** [comment]
Obrigado pela resposta! Uma abordagem que eu venho utilizando é a seguinte:

Os meus UseCases estão na minha camada de domínio. Quando ocorre de um UseCase precisar acessar um outro BC, isso é feito através de um **serviço de domínio**. Pensando dessa forma, o BC de `Customer` teria um serviço de domínio `IRegisterCustomerDomainService` com os seguintes métodos:
- um `OpenCheckingAccount` que me retornaria o `accountId`
- um `CreateUserCredentials` que me retornaria o `user`

De forma semelhante, o Core/SharedKernel do meu `Domain` teria um `IUnitOfWork` que seria responsável por garantir a integração entre os BCs numa mesma transação (pensando num caso onde ACID seria possível).

Nesse caso o `RegisterUseCase` estaria no domínio e acessaria o meu `IRegisterCustomerDomainService` para executar os comandos/queries nos outros BCs.

Por fim, dessa forma, aconteceria o seguinte:
- a implementação de `IUnitOfWork` estaria no layer de `Infrastructure`
- a implementação do(s) `IRegisterCustomerDomainService` estaria em um layer de `Services` ou até mesmo no de `Application`
- com isso, o `RegisterUseCase` ficaria no BC de `Customer` e a interação com os outros BCs seria através desse serviço de domínio.

O que acha dessa abordagem?!

**Comment by ivanpaulovich** [comment]
> De forma semelhante, o Core/SharedKernel do meu `Domain` teria um `IUnitOfWork` que seria responsável por garantir a integração entre os BCs numa mesma transação (pensando num caso onde ACID seria possível).

Com essa info eu percebo que fica difícil colocar o `IUnitOfWork` no `Domain` porque ele pertence a todos os BCs, considero a mesma analise para a implementacao dos `Use Cases`.

> * a implementação de `IUnitOfWork` estaria no layer de `Infrastructure`

Eu concordo.

> * a implementação do(s) `IRegisterCustomerDomainService` estaria em um layer de `Services` ou até mesmo no de `Application`

Eu colocaria no Domain.

> * com isso, o `RegisterUseCase` ficaria no BC de `Customer` e a interação com os outros BCs seria através desse serviço de domínio.

Faz sentido, a dificuldade que vejo é pensar nessa separacao para cada use case. Se você consegue identificar em qual BC o use case vai entrar entao de boa.

> O que acha dessa abordagem?!

A implementacao que eu sigo é bem classica quanto a layers (UI - Application - Domain - Infra), tirada do livro IDDD e fica facil comunicar com outros devs sobre esse modelo. Outras propostas divisoes de camadas geram uma fricçao na comunicacao entre os devs.

Colocando mais pimenta na discussao. Considerando a estrutura atual do Manga, uma sugestãoé colocar as interfaces dos casos de uso dentro dos BCs que fazem mais sentido:

- IRegisterUseCase e GetCustomerDetails dentro de `Customers`.
- IDepositUseCase, IWithdrawUseCase, ITransferUseCase e etc dentro de `Accounts`.

Um principio importante do Clean Architecture é colocar os casos de uso em destaque.. por isso eles estao no Application/UseCases e no futuro na raiz do `Application`.

E vamos ter me mente que essas propostas de separacao em camadas são apenas **organizacao de pastas**. 

Comportamento >> Estrutura.

Em um dia você consegue mudar a estrutura de uima aplicacao, comportamento leva tempo.
Adote uma organizacao que funcione e boa!

**Comment by mviegas** [comment]
Opa!

> Com essa info eu percebo que fica difícil colocar o IUnitOfWork no Domain porque ele pertence a todos os BCs, considero a mesma analise para a implementacao dos Use Cases.

Então, eu adoto a estrutura de um Core/Shared Kernel que é aquela parte do domínio comum à todos os BCs. No fundo, é um projeto `Domain.Core` que o `Domain` de cada BC referencia. Então isso acaba que resolve esse problema!

> uma sugestãoé colocar as interfaces dos casos de uso dentro dos BCs que fazem mais sentido

Isso é um caminho legal também, acho que inclusive dessa forma a gente consegue adotar uma coisa mais YAGNI/KISS e evita de ficar inventando subcamada atrás de subcamada. 

Eu implemento os meus UseCases de forma diferente, uso através do pattern _mediator_, com a interface sendo um _command_ e sua implementação um _handler_. Seguindo a sua proposta, os comandos ficariam no `Domain` e os handlers no `Application`. Acho que esse caminho de interfaces/comandos no `Domain` e sua implementação no `Application` deixa as responsabilidades bem definidas!

> E vamos ter me mente que essas propostas de separacao em camadas são apenas organizacao de pastas. Comportamento >> Estrutura. Em um dia você consegue mudar a estrutura de uima aplicacao, comportamento leva tempo Adote uma organizacao que funcione e boa!

Concordo 110% contigo! Só pra deixar registrado pra quem acompanha, que essa discussão estrutural no fundo é quase que "irrelevante" pois é meramente organização de pastas. Levantei ela aqui pra trocar uma idéia mesmo.

Obrigado pela troca de idéias aqui Ivan! O Clean Architecture Manga é um baita projeto de referência.

**Comment by vmamore** [comment]
Fala @ivanpaulovich beleza?

Nas actions dos controller são instanciadas as VOs que serão passadas para dentro dos inputs, gostaria de entender pq vc optou por instanciá-las dentro da controller ao invés de instaciá-las dentro dos inputs.

Exemplo de como seria:
```c#
        public async Task<IActionResult> Close(
            [FromServices] IMediator mediator,
            [FromServices] CloseAccountPresenter presenter,
            [FromRoute] [Required] CloseAccountRequest request)
        {
            var input = new CloseAccountInput(request.AccountId);
            await mediator.PublishAsync(input);
            return presenter.ViewModel;
        }
```

Dentro do CloseAccountInput:
```c#
        public CloseAccountInput(Guid accountId)
        {
            this.AccountId = new AccountId(accountId);
        }
```
 Isso faz sentido? Você vê alguma vantagem por evitarmos de ter a referência ao Dominio nas controllers? 

Valeu!

**Comment by ivanpaulovich** [comment]
Olá @vmamore,

Demorei em responder porque essa semana aqui esta uma loucura :)

A regra que eu sigo ao modelar as classes de Input/Output é simplesmente **não transferir objetos mutaveis como aggregates e entities**. Gostei da sua implementacao em criar os inputs a partir dos tipos primitivos (string, decimal, datetime) e internamente instanciar os value objects. 

Fique atento apenas para nao trazer objetos mais complexos, ou annotations.

> Isso faz sentido? Você vê alguma vantagem por evitarmos de ter a referência ao Dominio nas controllers?

Faz sentido. E um PR pro Manga com essa abordagem é bem vindo.

**Comment by leandrofagundes** [comment]
@ivanpaulovich tudo bem?

Eu tenho na minha Infrastructure um serviço externo, digamos que o Google Maps. Eu vou criar métodos para interagir de forma conveniente pro meu sistema com a api do google maps. Nesse caso, minha Application tem uma interface de contrato com o que espero que minha DLL que conecte ao google maps implemente.
Até aí tudo bem, mas como devo chamar as classes que contém os dados que saem do meu caso de uso pra DLL dos maps, e a classe que vai retornar a consulta no Google Maps. O Google Maps retorna um Json mas queria transformar isso em um objeto. Aonde fica esse objeto normalizado? Na DLL da application ou na do domain? Seria uma DTO?

**Comment by zander-br** [comment]
Olá @ivanpaulovich parabéns pelo conteúdo. Fiquei apenas com um dúvida, na camada de domínio temos o nosso Aggregate que é uma classe `abstract` eu verifiquei que a construção da mesma está sendo feita na camada de infra, ao qual tem uma classe que herda da `Domain.Account` essa abordagem não deixa o domínio frágil? Uma fez que no domínio temos que garantir a construção de um objeto válido sempre.

Caso falei alguma besteira me desculpe, porém ficaria felizes se alguém pudesse ajudar entender esse ponto. Estou estudando sozinho, e muitas vezes fico mais perdido do que tudo.

**Comment by leandrofagundes** [comment]
Opa @zander-br blza? 
Eu não tenho nem metade do conhecimento do @ivanpaulovich, mas sempre quis ajudar ele aqui no projeto de alguma forma, então vamos ver se não falo besteiras tb hehehehe.

Eu visualizo da seguinte forma, as regras mais definidas para a classe do domínio vão ser descritas na classe abstract. Por exemplo, ao criar uma conta, a data de nascimento tem que ser maior de 18 anos. 
A classe base (abstract) pode ter um constructor protected e nesse construtor tu vai validar se ele tem mais ou menos de 18 anos. A regra está na camada do domínio e não na camada de infra.

Mas por quê são feitas essas classes de infra? Eu entendo que cada infra (cache db, mongo, sql server, memória) tem seu jeito de persistir o dado e algumas regras particulares dessa infra. Imagina que um dia tu invente o Zander Database, uma tecnologia nova, mas que tu só persiste na base objetos que herdam de uma determinada classe q tu inventou. Tu faria a classe de domínio herdar da tua classe base? Ai tu feriria a ideia de que a gente não pode depender de infra. Então tem uma classe de domínio 100% protegida e deve ser herdada (abstract) por alguma classe de infra e essa sim será persistida.

Essa é a visão que eu assumi, e tem funcionado pra mim. Se o @ivanpaulovich quiser complementar é sempre melhor né hehe mas espero ter feito sentido pelo menos.

abraços

**Comment by zander-br** [comment]
Opa @leandrofagundes.

Muito obrigado pela a sua ajuda, eu acredito que eu entendi sim o conceito, para exercitar isso eu criei um pequeno exemplo, só para ver se tinha fixado.

*Interface ICustomer (Domínio)*

```csharp
using System;
namespace Manga
{
    public interface ICustomer
    {
        Guid Id { get; }
        string Name { get; }
        int Age { get; }

        void ChangeAge(int age);
    }
}
```

*Abstract Customer (Domínio)*

```csharp
using System;
namespace Manga
{
    public abstract class Customer : ICustomer
    {
        public Guid Id { get; protected set; }
        public string Name { get; protected set; }
        public int Age { get; private set; }

        protected Customer(int age)
        {
            if(age < 18)
            {
                throw new Exception("Customer must be over 18 years of age");
            }

            Age = age;
        }

        public void ChangeAge(int age)
        {
            if (age < 18)
            {
                throw new Exception("Customer must be over 18 years of age");
            }

            Age = age;
        }
    }
}
```

*Customer (Infra)*

```csharp
using System;
namespace Manga
{
    public class CustomerInMemory : Customer
    {
        public CustomerInMemory(Guid id, string name, int age)
            :base(age)
        {
            Id = id;
            Name = name;
        }
    }
}
```

Então pelo que entendi, as minhas regras de negócios ficariam tudo na minha classe abstrata e caso eu precise construir algum objeto com certas informações eu crio um construtor `protected` na minha classe abstrata **exigindo** esses valores certo? Nesse meu exemplo eu criei como se a minha propriedade `Age` fosse parte da minha regra, e para isso eu também coloquei ela como `private set` na minha classe abstrata, e criei um método para alterar a mesma, aplicando a regra do meu negócio. Você diria que isso é ser **purista** de mais?

**Comment by leandrofagundes** [comment]
Hehe então @zander-br  como falei, seria melhor se o @ivanpaulovich  desse a palavra final, mas é isso que eu entendo. Sobre ser *purista* de mais, um dia eu acreditei que isso existia, e depois eu comecei a perceber que eu não queria ser *purista* por preguiça, e dai percebi aonde estava (pelo menos no meu caso particular).
:)

**Comment by ivanpaulovich** [comment]
Ola @leandrofagundes @zander-br, eu precisei ficar umas semanas longe do PC e obrigado @leandrofagundes por guiar novos devs no projeto, valeu!

Sim, o estilo de codigo no Manga é purista. Em outros projetos de referencia você vai notar que os frameworks "ajudam/alteram" o desenho das classes de negocio. No Manga a interferencia é minima.

A responsabilidade do Domain é manter as regras de negocio em alto nivel, muitos devs concordam que o Domain nao deve se preocupar com "Persistencia de Dados". 

Ja a infrastrutura tem a responsabilidade de manter o estado da aplicacao e comunicar com dispositivos externos.

@zander-br, algumas alteracoes que fiz no seu codigo. Veja:
 
````c#
using System;
namespace Domain
{
    public interface ICustomer
    {
        Guid Id { get; }
        string Name { get; }
        int Age { get; }

        void ChangeAge(int age);
    }

    public abstract class Customer : ICustomer
    {
        public abstract Guid Id { get; protected set; }  // abstract modifier
        public abstract string Name { get; protected set; } // abstract modifier
        public abstract int Age { get; private set; } // abstract modifier

        public void ChangeAge(int age)
        {
            if (age < 18)
            {
                throw new Exception("Customer must be over 18 years of age");
            }

            Age = age;
        }
    }

   public interface ICustomerFactory
   {
        ICustomer NewCustomer(int sge);
    }
}
```

````c#
using System;
namespace Infrastructure.DataAccess
{
    public sealed class EntityFactory : ICustomerFactory
    {
        public ICustomer NewCustomer(int age)
        {
             return new Customer(age);
        }
    }

    public sealed class Customer : Domain.Customer
    {
        public Customer()
        {
        }

        public Customer(int age)
        {
            if(age < 18)
            {
                throw new Exception("Customer must be over 18 years of age");
            }

            this.Age = age;  // I moved the guard clause to the factory EntityFactory
        }

        public override string Name { get; }
        public override int Age { get; }
        public override Guid Id { get; }
    }
}
```

**Comment by zander-br** [comment]
Muito obrigado pela resposta @leandrofagundes  e @ivanpaulovich, porém @ivanpaulovich acredito que eu esteja um pouco perdido nesse conceito. Também concordo com você em deixar o nosso domínio agnóstico a detalhes de banco de dados por exemplo. Porém a minha grande dúvida é a seguinte, caso o meu sistema tenha por exemplo a regra de negócio de permitir criar uma conta maiores de 18 anos, essa regra deveria estar no meio domínio certo? Na construção do meu objeto de domínio, porém na sua modificação essa responsabilidade de certa forma não ficou na nossa **Infraestrutura**? Pois o nosso domínio tem apenas a responsabilidade de validar a alteração desse valor e não a sua construção. Estou errado em pensar dessa forma?

**Comment by leandrofagundes** [comment]
@ivanpaulovich venho aqui pq definitivamente me tranquei e não consigo me livrar dessa dúvida depois de alguns dias batendo cabeça, indo e voltando.

Quando fazemos no controller a conversão dos dados da requisição pra ValueObjects, podemos ali naquele momento que uma exceção seja disparada (se o value object não estiver válido).

Se ocorrer isso, o erro retornado pra api é uma exception. Agora não sei se devo fazer a tratativa no controller ou se o valueobject deveria estar mais dentro (na factory ou na domain).

Consegue me explicar qual é a expectativa?

**Comment by ivanpaulovich** [comment]
Oi @leandrofagundes,

Para tratar errors de conversao de Request em Input na WebApi você pode adicionar um filtro e retonar um `BadRequest` response.

**Comment by zander-br** [comment]
Olá @ivanpaulovich e à todos que puderem colaborar, estou a alguns dias estudando sobre arquitetura limpa e como parte dos meus estudos tenho dedicado um tempo para essa implementação, porém tenho tido algumas dúvidas a cerca da responsabilidade da camada de domínio. Na camada de domínio temos a interface da nossa **factory** ao qual está sendo implementada na nossa **infra**. Porém caso eu tenha um **Aggregate** de pedidos e um dos métodos para criação disponível seja, **Criar pedido rascunho** ao qual é uma regra de negócio setar o pedido como rascunho. Essa responsabilidade de criar o objeto dessa forma continuaria com a **infra** se alguém puder me ajudar nesse ponto serei muito grato, pois a dias estou quebrando a cabeça para entender isso.

**Comment by BrunoRM** [comment]
Como ficaria a implementação de uma query que agrega informações de vários objetos do domínio? Ou até mesmo de projeções que podem gerar consultas muito complexas e que não retornam objetos de domínio específicos?

Vejo que o padrão de Query Objects é uma boa pra esse tipo de problema. Neste caso eu criaria uma interface IQuery na camada de application e faria a implementação na camada de infraestrutura? 

Ou seria viável criar um use case e utilizar sql plain na camada de application mesmo?

**Comment by leandrofagundes** [comment]
Pessoal, ontem rolou uma live totalmente em português aonde o @ivanpaulovich participou.
Caso alguém tenha interesse, segue o link:

https://youtu.be/Lu2knlx-pu4

**Comment by leandrofagundes** [comment]
Opa @ivanpaulovich , eu tenho percebido que muitos awaits possuem o configureawait(false) no final.
Eu dei uma pesquisada e em resumo eu vejo o pessoal explicando que um ConfigureAwait(true) é quando você vai envolver UI e o false quando é mais dlls de backend, mas mesmo ouvindo e reouvindo as explicações não consegui compreender de fato a diferença e pra que serve.
Você poderia explicar?

**Comment by ivanpaulovich** [comment]
Ola @leandrofagundes,

Recomendo consultar o https://devblogs.microsoft.com/dotnet/configureawait-faq/ pois isso depende do tipo de aplicações que voce esta desenvolvendo, em geral temos:

Ao usar `ConfigureAwait(true)` o processamento assíncrono, seja esse realizar uma requisição HTTP ou executar uma consulta em banco de dados sera executado usando o mesmo Thread (ou Contexto de Sincronização) em uso no momento da chamada. Se o programa realizar muitas chamadas assíncronas demoradas a aplicação pode atingir um Deadlock.

Ao usar `ConfigureAwait(false)` o programa ira executar o código assíncrono em um Contexto independente. O que usa melhor os recursos do sistema.

**Comment by pauloafpjunior** [comment]
> Olá @maikmb,
> 
> O que o projeto mais precisa no momento é de uma interface de usuário (React, Blazor, etc). Se tiver interesse nisso seria bem vindo.
> No mais, fazendo perguntas já está ajudando bastante.

Falando em UI, @ivanpaulovich, você acha possível ou que há algum benefício em aplicar os princípios de Clean-arch em código front-end? Conhece algum projeto interessante com Angular, por exemplo?

**Comment by ivanpaulovich** [comment]
Hey @pauloafpjunior, eu acho que a produtividade no frontend é muito dependente de frameworks e que vale a pena usufruir desse beneficio. 

Não conheço uma referência em Angular.

Obrigado e seja bem vindo :)

**Comment by pauloafpjunior** [comment]
> Hey @pauloafpjunior, eu acho que a produtividade no frontend é muito dependente de frameworks e que vale a pena usufruir desse beneficio.
> 
> Não conheço uma referência em Angular.
> 
> Obrigado e seja bem vindo :)

Eu que agradeço a reposta e parabéns pelo trabalho. Tens algum livro publicado sobre o assunto? Acho que terias muito a contribuir...

**Comment by agpcardoso** [comment]
Olá, o que difere  os UseCases dos Application Services do DDD?

**Comment by ivanpaulovich** [comment]
> Olá, o que difere os UseCases dos Application Services do DDD?

Ola @agpcardoso, essencialmente Application Services e Casos de Usos são pontos de entrada para a execução das regras de negócio. Fisicamente são a mesma coisa: interfaces + implementação.

No ponto de vista de Clean Architecture, as regras de negocio são **organizadas ao redor dos casos de uso**. Essa característica implica: 

- na organização de pastas.
- no baixo desacoplamento entre casos de usos.
- na nomenclatura.

**Comment by marcrib** [comment]
@ivanpaulovich Olá, parabéns pelo projeto. Verifiquei em outra issue o motivo de você não usar o MediatR (não ter dependências). 
Mas como você trataria eventos de domínio? Por exemplo, como notificaria um novo depósito por e-mail?

**Comment by leandrofagundes** [comment]
> @ivanpaulovich Olá, parabéns pelo projeto. Verifiquei em outra issue o motivo de você não usar o MediatR (não ter dependências).
> Mas como você trataria eventos de domínio? Por exemplo, como notificaria um novo depósito por e-mail?

@marcrib  nesse caso, creio que a melhor saída seja você injetar a depêndencia necessária.
Crie uma interface na sua aplicação/domínio com os métodos necessários, e a implementação na camada mais externa.
Dessa forma, sua aplicação/domínio dependem apenas da Interface, e sua classe de implementação que de fato depende de outros frameworks, está na camada mais externa. Se aplicar certinho, o dia que for necessário trocar seu serviço de eventos, basta que o novo implemente a interface da mesma forma e esse novo serviço seja injetado ao invés do anterior.

**Comment by marcrib** [comment]
> t

Praticamente criando um adapter para o BUS ?

**Comment by marcrib** [comment]
> > @ivanpaulovich Olá, parabéns pelo projeto. Verifiquei em outra issue o motivo de você não usar o MediatR (não ter dependências).
> > Mas como você trataria eventos de domínio? Por exemplo, como notificaria um novo depósito por e-mail?
> 
> @marcrib nesse caso, creio que a melhor saída seja você injetar a depêndencia necessária.
> Crie uma interface na sua aplicação/domínio com os métodos necessários, e a implementação na camada mais externa.
> Dessa forma, sua aplicação/domínio dependem apenas da Interface, e sua classe de implementação que de fato depende de outros frameworks, está na camada mais externa. Se aplicar certinho, o dia que for necessário trocar seu serviço de eventos, basta que o novo implemente a interface da mesma forma e esse novo serviço seja injetado ao invés do anterior.

Praticamente criando um adapter para o BUS ?

**Comment by ivanpaulovich** [comment]
> > > @ivanpaulovich Olá, parabéns pelo projeto. Verifiquei em outra issue o motivo de você não usar o MediatR (não ter dependências).
> 
> > > Mas como você trataria eventos de domínio? Por exemplo, como notificaria um novo depósito por e-mail?
> 
> > 
> 
> > @marcrib nesse caso, creio que a melhor saída seja você injetar a depêndencia necessária.
> 
> > Crie uma interface na sua aplicação/domínio com os métodos necessários, e a implementação na camada mais externa.
> 
> > Dessa forma, sua aplicação/domínio dependem apenas da Interface, e sua classe de implementação que de fato depende de outros frameworks, está na camada mais externa. Se aplicar certinho, o dia que for necessário trocar seu serviço de eventos, basta que o novo implemente a interface da mesma forma e esse novo serviço seja injetado ao invés do anterior.
> 
> 
> 
> Praticamente criando um adapter para o BUS ?

Hey @marcrib, assim como o @leandrofagundes ja explicou. O caso de uso pode delegar a o envio de notificações para a implementação da interface `INotificationService` definida na sua Application 😄

**Comment by leandrofagundes** [comment]
@ivanpaulovich tem algumas coisas que ainda não entram nessa cabecinha gigante aqui 😢 

Eu tenho uma entidade (Oferta) que só deve ter dados em uma tabela secundária (OfertaRegiao) quando ela de fato for lançada.
Ou seja, eu crio a oferta, dados dela, título, etc e deixo tudo pronto, mas ela ainda não foi lançada em nenhuma região do país.

Essa oferta fica disponível em uma lista de ofertas, e todos que querem adotar ela, executam o método Lançar na oferta, gerando um registro de OfertaRegiao. Esse registro tem o ID da oferta e os dados da região que ela vai cobrir (geolocation, etc).

Agora falando da estrutura. Meu OfertaFactory tem um Criar para criar a oferta e um Lancar para lançar na região (recebe a oferta e uma entidade de região).
Mas eu também preciso mudar uma propriedade na entitida Oferta, ficando assim:

`
oferta.Lancar();//muda o status
var ofertaRegiao = ofertaFactory.Lancar(oferta,regiao);//cria um ofertaRegiao que vai pra base

ofertaRepository.Update(oferta);//atualiza a oferta que sofreu alteração no status
ofertaRepository.AdicionarRegiao(ofertaRegiao);//que adiciona a região para oferta`

O que me incomoda é ter que manualmente chamar o model oferta para lançar, e depois chamar o factory para criar a região (chamando um lançar duas vezes).

Desculpa se não ficou clara a explicação, mas parece que tem algum code smell ai no meio.
Pode me dar um norte?
