### ISSUE TITLE
Design OutputBuilder class

### ISSUE THREAD

**Issue by ivanpaulovich** [ivanpaulovich/clean-architecture-manga#152]
Output messages could be complex and dependent on multiple steps to be created. What if we change the `BuildOutput()` method to a proper builder pattern?

https://github.com/ivanpaulovich/clean-architecture-manga/blob/4be82c23327e20cd922875cca274a3b50bd5e510/src/Application/UseCases/Withdraw.cs#L67

**Comment by vmamore** [comment]
Hey @ivanpaulovich, how are you?
I'm interested about this. The output classes can vary depending on the UseCase, do you think we should have one output builder for each UseCase or just one generic for all?

Thanks!

**Comment by ivanpaulovich** [comment]
Hi @vmamore,

I appreciate your interest in it!

I learned that the Builder would not bring benefits for the design. Let's freeze this issue until someone comes with a real issue to solve.

Best
