### ISSUE TITLE
Using structs or classes as base for Value Objects?

### ISSUE THREAD

**Issue by mabako** [ivanpaulovich/clean-architecture-manga#154]
Hey,

I've found a slight issue which I'm not entirely sure can be addressed in .NET, but essentially, structs can be initialized as `default(...)`, regardless of what constructors exist.

Thus, I can easily create a SSN and (all other value objects) by using

```
SSN ssn = default;
```

While this may work fine if you're relying on everyone initializing these value objects using their constructor, would it not be better to make SSN, Name, etc. classes?

You could, in theory, also use `SSN ssn = new SSN()`, but that is a stylecop error and not a .NET error.

**Comment by ivanpaulovich** [comment]
Hey @mabako, I didn't know about this usage. It is fine to use classes, maybe it is better.
