### ISSUE TITLE
Target .NetCore 3.1 on Library Projects

### ISSUE THREAD

**Issue by douglasramos** [ivanpaulovich/clean-architecture-manga#162]
@ivanpaulovich what do you think about using .net core 3.1 as a target for library projects as well? Some features of C # 8.0 apparently only work on  .NET core 3.0/3.1. For example, NullableReferenceType doesn't work as expected. I tried myself. This link has a little more info about this: https://stu.dev/csharp8-doing-unsupported-things/.

**Comment by ivanpaulovich** [comment]
Hey @douglasramos,

I appreciate the attention to the details and the link with information I wasn't aware about.

I am looking forward to make **NullableReferenceTypes** work as expected on this project, even more [I'd like to see it to work seamless with FxCopAnalyzers](https://github.com/dotnet/roslyn-analyzers/issues/2875).

It seems that maintaining compatibility with .NET Framework is not a reality. 

Let's do like this, if there is a PR with C#8 improvements that requires target 3.1 then we will upgrade those projects.

**Comment by douglasramos** [comment]
@ivanpaulovich, great, that is fair!
