### ISSUE TITLE
Encapsulate annotations on Controllers

### ISSUE THREAD

**Issue by douglasramos** [ivanpaulovich/clean-architecture-manga#163]
@ivanpaulovich, what do you think about encapsulating the annotations that are repeated between the different controllers of the application? In this way, we could apply the  DRY principle, in a better way. We could create a base class for the controllers and also make use of API conventions.

**Comment by ivanpaulovich** [comment]
Hey @douglasramos,

I added a PR to reduce the repeated code https://github.com/ivanpaulovich/clean-architecture-manga/pull/164/files

I'd consider one thing before merging those controllers:

I am afraid of huge controllers, so I prefer to start a new feature on new files. If you check the combo Model-Controller-Presenter, the code are very specific to one use case.

But I am open minded, how the conventions would work?

**Comment by douglasramos** [comment]
@ivanpaulovich, we could start using api conventions, without a base controller. With api conventions, we could remove generic ProcedureResponse Annotation from each controller method. That alone is a good improvement. Here's the link about api conventions: https://docs.microsoft.com/en-us/aspnet/core/web-api/advanced/conventions?view=aspnetcore-3.1

**Comment by ivanpaulovich** [comment]
Conventions sounds interesting 😎!
Would you open a PR with your implementation?

**Comment by ivanpaulovich** [comment]
Hi @douglasramos,

We added conventions on the latest changes https://github.com/ivanpaulovich/clean-architecture-manga/pull/216/files
We can still improve it by using naming conventions. Please check it out and would be nice if you come up with ideas.

Best

**Comment by ivanpaulovich** [comment]
Included on https://github.com/ivanpaulovich/clean-architecture-manga/pull/220
