### ISSUE TITLE
Placement choice of property CustomerId

### ISSUE THREAD

**Issue by schipani** [ivanpaulovich/clean-architecture-manga#166]
Hello Ivan,

Could you please explain your reasoning for the placement choice of property CustomerId on the inherited class Infrastructure.EntityFrameworkDataAccess.Account rather than base Domain.Accounts.Account?

The Aggregate Roots design pattern as you mentioned suggest that groups of logical objects be kept together and treated as a single unit of data and that everything should flow through that root object to maintain integrity.

[https://github.com/ivanpaulovich/clean-architecture-manga/wiki/Domain-Driven-Design-Patterns#aggregate-root](https://github.com/ivanpaulovich/clean-architecture-manga/wiki/Domain-Driven-Design-Patterns#aggregate-root)

My first instinct would have been to place CustomerId at the Domain level rather than Infrastructure and i'm curious to know if this was a design choice with reasoning, and if so, what that reasoning was.

**Comment by ivanpaulovich** [comment]
Hey @schipani,

Sorry for the late response. Let me clarify the design.

The Manga has two Models:

1. Domain Model - objects that expose behaviours for use cases.
2. Data Model - adds persistence for the Domain Model.

Until now no use cases needed to know the Customer from an Account, instead these use cases see the relationship *a Customer has a list of accounts*.

The CustomerId property exist on `Infrastructure.EntityFrameworkDataAccess.Account` only to persist the relationship customer-account. This is a Data Model concern, not Domain Model concern (at this time).

> The Aggregate Roots design pattern as you mentioned suggest that groups of logical objects be kept together and treated as a single unit of data and that everything should flow through that root object to maintain integrity.

If one Aggregate Root needs to know another one it should know his ID. It does not mean that every aggregate root should be connected.
