### ISSUE TITLE
Web interface

### ISSUE THREAD

**Issue by NicoCG** [ivanpaulovich/clean-architecture-manga#17]
Hello,

Could you kindly publish a web interface like the example below?

https://github.com/EduardoPires/EquinoxProject/tree/master/src/Equinox.UI.Site

Or could you show me of an example someone has done.

**Comment by ivanpaulovich** [comment]
Hi @NicoCG!
Do you mean an MVC Web Interface? It's a good idea and I'll publish next days :)

**Comment by NicoCG** [comment]
@ivanpaulovich Yes MVC Web Interface

> It's a good idea and I'll publish next days :)

Happy to hear that and excited to see it.

**Comment by ivanpaulovich** [comment]
Hello @NicoCG!

I added the MVC User Interface with Feature Folders setup.
The main use cases are implemented and tested for the InMemory Data Access.

Happy coding :)

**Comment by NicoCG** [comment]
@ivanpaulovich Thank you
