### ISSUE TITLE
How can you modify a property?

### ISSUE THREAD

**Issue by Blackleones** [ivanpaulovich/clean-architecture-manga#171]
I've noticed that there isn't a use case with that makes possible to change a property like a Customer name. How would you implement this use case? 

- (A) changing the property setter from `protected set` to `set` so you can change the customer name like `costumer.Name = new Name("MyName")`
- (B) add a new method to `ICustomer` like `void ChangeName(Name name)` ?

I think the (B) solution is the best because you use the _Open Close principle_ but at the same time if you have an Entity with a lot of properties, then you have an interface with a lot of "setter methods".

**Comment by qpippop** [comment]
> I think the (B) solution is the best because you use the _Open Close principle_ but at the same time if you have an Entity with a lot of properties, then you have an interface with a lot of "setter methods".
Or you can use properties with backing fields...

**Comment by ivanpaulovich** [comment]
Hey @Blackleones,

It is funny that we didn't implement the "Update Customer Information Use Case". Starting from the current design you will need to create a "ICustomer.UpdateDetails(SSN ssn, Name name)". 

I'd suggest you to not create individual property setters. Instead design methods that group these changes together as the use case will probably change multiple properties at the same time.

**Comment by Blackleones** [comment]
I agree with you. However,

> Instead design methods that group these changes together as the use case will probably change multiple properties at the same time.

Doesn't it violate the _Single responsibility principle_? Because if I want to update only the SSN property then I have to update the name, and vice-versa.

**Comment by ivanpaulovich** [comment]
> Doesn't it violate the _Single responsibility principle_? Because if I want to update only the SSN property then I have to update the name, and vice-versa.

No. It doesn't. SRP is about a class being responsible for a single Actor. The Customer class is responsible for few use cases. 

I am considering that the use cases is *The Customer updates his personal details*. Or do you plan to design *Update Customer Name Use Case* all the way up to the user?

**Comment by Blackleones** [comment]
Thank you!

I've just asked to verify if I understood because I am learning the Clean Architecture. So I that the answer to my question depends on the use case, as you told me.
