### ISSUE TITLE
Broken Image in Separation of Concerns

### ISSUE THREAD

**Issue by vijaysg** [ivanpaulovich/clean-architecture-manga#176]
Page https://github.com/ivanpaulovich/clean-architecture-manga/wiki/Separation-of-Concerns has a broken link pointing to image https://raw.githubusercontent.com/ivanpaulovich/clean-architecture-manga/master/docs/clean-architecture-manga-layers.png which is a 404.

I thought of editing it, but I was [unable to find](https://github.com/ivanpaulovich/clean-architecture-manga/search?q=clean-architecture-manga-layers.png&unscoped_q=clean-architecture-manga-layers.png) the image in the repo

**Comment by leandrofagundes** [comment]
Hi @vijaysg, I believe it's an image from Clean Architecture layers, but I'm not sure.
https://static.imasters.com.br/wp-content/uploads/2018/10/07222901/conn.jpg

Let's wait for @ivanpaulovich to answer this one

**Comment by ivanpaulovich** [comment]
HI @vijaysg,

The image you are looking for is available here https://raw.githubusercontent.com/ivanpaulovich/clean-architecture-manga/docs/docs/clean-architecture-manga-layers.png

**Comment by ivanpaulovich** [comment]
Wiki page updated to include the correct image.
