### ISSUE TITLE
Foreign Key

### ISSUE THREAD

**Issue by pendenaor** [ivanpaulovich/clean-architecture-manga#193]
Hi,

Maybe i am missing something, but in your EFCore configuration file, i didn't see any foreign keys, is it on purpose ?

My project has several tables with
```
entity.HasOne(e => e.Parent)
                .WithMany(p => p.Children)
                .HasForeignKey(d => d.ParentId);
```
types of configuration. How do i transform that ?

**Comment by ivanpaulovich** [comment]
Hi @pendenaor,

Our implementation is missing the configuration that tells Entity Framework how to build the SQL foreign keys. This mapping needs to be added to `AccountConfiguration.cs` and `CustomerConfiguration.cs` and you are welcome to open a PR including this :)

Best

**Comment by pendenaor** [comment]
Thanks. I would try.
