### ISSUE TITLE
Fix Warnings

### ISSUE THREAD

**Issue by ivanpaulovich** [ivanpaulovich/clean-architecture-manga#199]
Please enable the rule checks and fix the codebase. 

https://github.com/ivanpaulovich/clean-architecture-manga/blob/ede62886981b6bf1f093cb352936b84c0518a3c2/src/WebApi/WebApi.csproj#L17

**Comment by vmamore** [comment]
Hey @ivanpaulovich,
I'm going to work on this, right now I'm reading the [OSS guide](https://opensource.guide/) to understand better how to behave. Do we have a pattern to create branch? Any doubt about the class design should I post here?

Thanks!

**Comment by ivanpaulovich** [comment]
Hi @vmamore,

You are more than welcome to contribute! Feel free to ask, review the Wiki, contribute by improving the tests and codebase.

We maintain two branches:

- [Latest .NET Core 3.1 release](https://github.com/ivanpaulovich/clean-architecture-manga) - Check the .NET Core SDK **version** on `global.json`.
- [.NET 5](https://github.com/ivanpaulovich/clean-architecture-manga/tree/dotnet5) - Experimental features and .NET 5.

We don't have strict branch naming rules.

Post here questions about fixing the warnings. Open new issues for specific questions.

Thanks for contributing!

**Comment by vmamore** [comment]
Hey @ivanpaulovich, I removed the "<NoWarn>" inside the csproject and now I'm fixing the warnings.

Should I verify in all method the parameters are null like I did with **_CloseAccountRequest request_** or do you have a better example?
![image](https://user-images.githubusercontent.com/26505439/84958096-951fe800-b0ca-11ea-94ac-7d8b0e0c605f.png)
(The exception class is just for example purpose)

I'm thinking that this will get really repetitive.

Thanks!

**Comment by ivanpaulovich** [comment]
Hi @vmamore,

We need to verify all nullable parameters. For this methods we require:

```
if (request is null)
{
    throw new ArgumentNullException(nameof(request));
}

if (getAccountsPresenter is null)
{
    throw new ArgumentNullException(nameof(getAccountsPresenter));
}

if (mediator is null)
{
    throw new ArgumentNullException(nameof(mediator));
}
```

This issue affects many many files. So I suggest remove 2 or 3 rules from the NoWarn tag and fix them, because fixing them all could affect a thousand files.

Thanks!
