### ISSUE TITLE
Failed to compile: Cannot find name 'connect'. TS2304

### ISSUE THREAD

**Issue by Waldulmer** [ivanpaulovich/clean-architecture-manga#223]
Installing the project locally I receive the following Typescript error. Do you have suggestion how to overcome?
![image](https://user-images.githubusercontent.com/22600469/89663861-3db91f80-d8a4-11ea-8cdc-9eebb7adb8b3.png)

**Comment by GarthOrmsby** [comment]
@Waldulmer - I'm no React/UI coder but these changes worked for me to get the Home component working:
- add `import React, { Component } from "react";` to index.tsx, App.tsx, Home.tsx
- add `import { connect } from "react-redux";` to Deposit.tsx, Register.tsx, Withdraw.tsx

Hope that helps.

**Comment by ivanpaulovich** [comment]
Hey @Waldulmer,

Sorry, we lack UI tests and I keep introducing bugs in the React. I will be more careful from now on.
Please try the latest version and this issue should be fixed.

Thanks!
