### ISSUE TITLE
On microservices, should the use case call the another service?

### ISSUE THREAD

**Issue by leandrofagundes** [ivanpaulovich/clean-architecture-manga#225]
Hi,

If I try a structure with microservices, should the use case call the other service or should be the API?
Is OK if my use case call another microservices (Rest API)?

**Comment by qpippop** [comment]
Hello @leandrofagundes,

I think it's definitely OK if it's part of the business logic (using some abstraction like `IFriendlyService` and implementing it in the infrastructure layer).

**Comment by leandrofagundes** [comment]
Hi @qpippop thanks for participating,

so, thinking about a monolyth, where I have many modules and contexts.
If I need to run a rule from a specific module from another module, can one Use Case call another Use Case implementing it as a service or should all the rule about one use case be done inside itself?

**Comment by qpippop** [comment]
Every use case is piece of (isolated) business logic. So it can (and probably should) be combined if needed. However if you call `IUseCase` directly there could be difficulties with sharing (or not sharing) connections/transactions and other stuff. So i would implement special aggregator to accomplish this task. I can't answer how exactly without deep dive into concrete problem

**Comment by ivanpaulovich** [comment]
Very nice explanation @qpippop. I totally agree :)
