### ISSUE TITLE
CustomerReadOnlyRepository

### ISSUE THREAD

**Issue by MarlonMiranda** [ivanpaulovich/clean-architecture-manga#24]
Hi, 

I observed that the class **CustomerRepository** is with wrong name on implementation ( "CustomerReadOnlyRepository")

**Comment by ivanpaulovich** [comment]
Hi Marlon,

Could you share where you found the issue?

If the question is regarding classes like the following:

```
public class CustomerRepository : ICustomerReadOnlyRepository, ICustomerWriteOnlyRepository
{ 
//
}
```
Then I think it is correct. My intent is that the consumers of ICustomerReadOnlyRepository are seeing only the methods they need. That's the reason I applied `ISP` and spitted the interfaces in two.

On the other hand, the class implementation has the responsibility to consume the database and they implement both Reading and Writing methods.

What do you think?
/Ivan

**Comment by MarlonMiranda** [comment]
Hi Ivan, 

I think I expressed myself poorly.

I agree as to the function of the class, what I meant was that the class was named CustomerReadOnlyRepository when in this case it performs read and write operations, as distinguished in the interfaces ICustomerReadOnlyRepository, ICustomerWriteOnlyRepository.

In the case I am questioning if the name of the class, in this case, should not be only, CustomerRepository as well as AccountRepository.

No more, great code, thanks for sharing.

/Marlon



![image](https://user-images.githubusercontent.com/12774904/55027323-c30b9f00-4fe3-11e9-8618-8941915deb41.png)

**Comment by ivanpaulovich** [comment]
Hi @MarlonMiranda you are correct. And that was good catch!
Soon there will be a fix.
Regards,
Ivan

**Comment by ivanpaulovich** [comment]
@all-contributors please add @jakebolam for design and tests

**Comment by ivanpaulovich** [comment]
@all-contributors please add @MarlonMiranda for design and tests
