### ISSUE TITLE
./startup.sh failing on WebApi .Net 5

### ISSUE THREAD

**Issue by IsaacCalligeros** [ivanpaulovich/clean-architecture-manga#254]
Hi, I'm new to docker and trying to trying to run the solution with the commands listed in the readme. When running the startup.sh I get the below error. Not sure how the errors throwing since the WepApi docker file is targeting the 5.0 sdk. Any advice?

Step 5/6 : RUN dotnet restore "src/WebApi/WebApi.csproj"
 ---> Running in 8023c614b74b
  Determining projects to restore...
  Restored /src/src/Domain/Domain.csproj (in 14.45 sec).
  Restored /src/src/Application/Application.csproj (in 14.45 sec).
  Restored /src/src/Infrastructure/Infrastructure.csproj (in 35.78 sec).
  Restored /src/src/WebApi/WebApi.csproj (in 35.89 sec).
Removing intermediate container 8023c614b74b
 ---> 845124d2d746
Step 6/6 : RUN dotnet build "src/WebApi/WebApi.csproj" --no-restore
 ---> Running in 8182e54e95bb
Microsoft (R) Build Engine version 16.7.2+b60ddb6f4 for .NET
Copyright (C) Microsoft Corporation. All rights reserved.

/usr/share/dotnet/sdk/3.1.406/Microsoft.Common.CurrentVersion.targets(1177,5): error MSB3971: The reference assemblies for ".NETFramework,Version=v5.0" were not found. You might be using an older .NET SDK to target .NET 5.0 or higher. Update Visual Studio and/or your .NET SDK. [/src/src/WebApi/WebApi.csproj]

Build FAILED.

/usr/share/dotnet/sdk/3.1.406/Microsoft.Common.CurrentVersion.targets(1177,5): error MSB3971: The reference assemblies for ".NETFramework,Version=v5.0" were not found. You might be using an older .NET SDK to target .NET 5.0 or higher. Update Visual Studio and/or your .NET SDK. [/src/src/WebApi/WebApi.csproj]
    0 Warning(s)
    1 Error(s)

**Comment by charithdesilva** [comment]
fix added https://github.com/ivanpaulovich/clean-architecture-manga/pull/255

**Comment by ivanpaulovich** [comment]
Hey @IsaacCalligeros it has been a long time but I kindly ask you to check the latest version.
