### ISSUE TITLE
IdentityServer4 key rotation and management

### ISSUE THREAD

**Issue by brunohbrito** [ivanpaulovich/clean-architecture-manga#272]
Hi guys, this is an awesome project!! I really appreciate it!

I'm openning a issu to propose a change at [IdentityServer4 Signing Credentials](https://github.com/ivanpaulovich/clean-architecture-manga/blob/e8aa4e43db9c3952d20d5d74bb500f8e9ea0b8f2/identity-server/Startup.cs#L56)

This default component wasn't designed to AutoScaling and it generate a phisical key at root directory [tempkey.jwk](https://github.com/ivanpaulovich/clean-architecture-manga/blob/main/identity-server/tempkey.jwk). I saw the comment, but we can improve it and help developers who use manga.

There are some open source projects that solve the Key Management problem. With key rotation and offers ECDsa, RSA. 

If you approve I make a PR.

Cheers,.

**Comment by ivanpaulovich** [comment]
Hey @brunohbrito, really nice feedback!

I've been struggling to keep Identity Server up to date and I see it as a gate keeper stopping new developers to get started with CleanArchitectureManga. So I would not invest in upgrading of configuring Identity Server.

I actually plan to remove IS in favor of a cloud service some time soon.

Best,
Ivan

**Comment by brunohbrito** [comment]
Oh! I see... Personally I don't like IS for the same reason, it's complicated and hard to maintain.

I'm closing issue!!
