### ISSUE TITLE
Account Transfering

### ISSUE THREAD

**Issue by matiienkodimitri** [ivanpaulovich/clean-architecture-manga#31]
hello ivan, congrats for the nice job you ve done.
btw I ve read the code, and I miss an example of account transfering among two diffrents accounts.
how would it be done within that architectural approach?
May it be something related with Unit of Work?

**Comment by ivanpaulovich** [comment]
Hi @matiienkodimitri!

That's a good suggestion for a new use case :)
Yes, the UnitOfWork patttern is a good solution to decouple TransactionScope from the use cases.

I would say that the AccountTransferUseCase could call the repository twice inside an unitofwork scope.

Do you have an specific concern?
/Ivan

**Comment by matiienkodimitri** [comment]
Basicaly aggregate roots does not know one another, and they are also persistent ignorants.
transactions anyway are database related I was figuring out what would be the role of this Transaction Scope inside the character set of roles in DDD ( oggregates, entities, value objects , etc ... )

**Comment by ivanpaulovich** [comment]
Hi @matiienkodimitri :)

I agree with your consideration about Aggregate Roots. Let me show how I would do the TransferUseCase:

```
public async Task Execute(Input input)
{
    _unityOfWork.Begin();

    IAccount originAccount = await _accountRepository.Get(input.OriginAccountId);
    if (account == null)
    {
        _outputHandler.Error($"The account {input.AccountId} does not exist or is already closed.");
        return;
    }

    IAccount destinationAccount = await _accountRepository.Get(input.DestinationAccountId);
    if (account == null)
    {
        _outputHandler.Error($"The account {input.AccountId} does not exist or is already closed.");
        return;
    }

    IDebit debit = originAccount.Withdraw(input.Amount);
    ICredit credit = destinationAccount.Deposit(input.Amount);

    await _accountRepository.Update(originAccount, debit);
    await _accountRepository.Update(destinationAccount, credit);

    Output output = new Output(
        debit,
        originAccount.GetCurrentBalance());

    _outputHandler.Handle(output);

    _unityOfWork.Commit();
}
```

The UnitOfWork would be a service that the application only know by the interface and which the implementation resides in the infrastructure.

What would you think about it?

**Comment by matiienkodimitri** [comment]
Make sense , but what kind of role would it be? I mean if it is a application service, I think it would not have any business logic inside.

I aggree with your code, but perhaps it should be a Domain Service Method not an application service method.

gotcha?

**Comment by ivanpaulovich** [comment]
@matiienkodimitri I found the transfer use case and Unit Of Work pattern very interesting to implement so it is now available on master. 

Could you check the PR https://github.com/ivanpaulovich/clean-architecture-manga/pull/32/files ?

Soon I will answer your questions.

**Comment by ivanpaulovich** [comment]
@matiienkodimitri the **UnitOfWork** and **Repositories** are connected via the `DbContext` object which is injected on every request.

I would say that **UnitOfWork** and **Presenters** (`IOutputHandlers`) are application services in the DDD terminology.

What do you say?

**Comment by matiienkodimitri** [comment]
Hi Ivan, 
I ve took so long cuz I was vacation.
now I am back.

First of all, big thanks for all given attention. 

I ve read carefully your code, and I would like to discuss why should I have UnitOfWork in every single repository call ( and why would it be visible to every one in application layer - would n t it be nice if it was seamless ) 


I agree that transfers need to have UoW but why would n t it be seamless to all the others classes.


 
![image](https://user-images.githubusercontent.com/53822759/64531651-60366780-d2e6-11e9-8a1b-cca3fbb9cac3.png)

**Comment by ivanpaulovich** [comment]
@matiienkodimitri I hope you had a good vacation ;)

The `_unitOfWork.Save()` is called once per transactional use case. 

I can imagine two approaches to move the `Save()` to a single place.

1. Moving the `_unitOfWork.Save()` to the Controller level.
2. Creating a decorator for UseCases responsible for committing transactions. The same pattern from here: https://github.com/AdaptiveCode/Chapter4/tree/master/ch4-logging-decorator/TheInterface/LoggingDecorator

Both approaches you need to deal with error handling.

What do you think?

**Comment by matiienkodimitri** [comment]
to me seems to be, that if it happens every transactional use, it should be seamless to developers.

managed by architecture "under the hood".

**Comment by ivanpaulovich** [comment]
Hi @matiienkodimitri,

It is possible to have a default behavior for Use Cases but I don't see too much benefits from that.
I like the idea of the developer having control of whats if happening instead of "magic under the hood".

if you have a solution I would love to see.

Best

**Comment by ivanpaulovich** [comment]
@all-contributors please add @matiienkodimitri  for Design and Tests

**Comment by ivanpaulovich** [comment]
I am closing it as I don't have plans to add this behavior now.
Thank you @matiienkodimitri
