### ISSUE TITLE
README broken anchor links.

### ISSUE THREAD

**Issue by matheusneder** [ivanpaulovich/clean-architecture-manga#54]
Hey Mr. Ivan!

On [README.md](https://github.com/ivanpaulovich/clean-architecture-manga/blob/master/README.md), the links at [Index of Clean Architecture Manga](https://github.com/ivanpaulovich/clean-architecture-manga/blob/master/README.md#index-of-clean-architecture-manga) section are broken starting at [.NET Core](https://github.com/ivanpaulovich/clean-architecture-manga/blob/master/README.md#.net-core) item.

**Comment by ivanpaulovich** [comment]
Hi @matheusneder!

My priority for the next days is to build that documentation, soon the links will be fixed, new content will be created with examples and their motivations.

Obrigado :)

**Comment by ivanpaulovich** [comment]
Hi @matheusneder!

Links are working again and the readme is quite finished.

@all-contributors please add @matheusneder for tests.
