### ISSUE TITLE
I want to know better about it

### ISSUE THREAD

**Issue by matiienkodimitri** [ivanpaulovich/clean-architecture-manga#69]
Hi Ivan

I ve found something really interesting in your project Mango

![image](https://user-images.githubusercontent.com/53822759/64698726-ca334600-d479-11e9-8509-ba5b83414d6b.png)

I would like to talk detailed about it to future

**Comment by ivanpaulovich** [comment]
Hi @matiienkodimitri,
Feel free to ask :)

**Comment by ivanpaulovich** [comment]
Closing the issue for now
