### ISSUE TITLE
Feature Request: JWT Authentication

### ISSUE THREAD

**Issue by CodeWorldIndustries** [ivanpaulovich/clean-architecture-manga#87]
This is great work. Can you implement authorization and authentication best practices with JWT Authentication?

**Comment by ivanpaulovich** [comment]
Hey @CodeWorldIndustries!

Sorry for the late response. This is a recurrent question and I guess someone could add authorization/authentication to the WebAPI layer.

I would ask for a PR with Authentication/Authorization and see if there is help out there.

Best,
Ivan

**Comment by phmatray** [comment]
I'm looking into it now.
I use this article as a starting point.
https://jasonwatmore.com/post/2019/10/11/aspnet-core-3-jwt-authentication-tutorial-with-example-api

However, I wonder if I should add the properties "Username", "Password" and "Token" to the "Customer" of the "Domain" project.

For "Username" and "Password", no problem, I think it can fit into the domain. However, the Token seems to me to be a technical detail of implementation.... What would be the approach you would recommend @ivanpaulovich ?

**Comment by phmatray** [comment]
Currently the "Register" use-case is in charge of creating a new customer AND a new account linked to this new customer.

I think it would be appropriate to create a new UseCase named "Authenticate" and adapt the UseCase "Register" to limit it to the registration of an account.

**Comment by phmatray** [comment]
I achieve a result.
However, I still have some work to do before I can propose a pull request.
I still have to work on getting the jwtSecret from the AppSettings.

![jwt-clean-architecture](https://user-images.githubusercontent.com/9035444/68843248-1001ca00-06c8-11ea-8fa3-aadb187df913.png)

**Comment by ivanpaulovich** [comment]
Hey @phmatray!
I see that you added good stuff to the project, I am gonna review and run it on the next days, I am excited with your changes  :)

**Comment by ivanpaulovich** [comment]
JWT authentication added to the latest changes.
