### ISSUE TITLE
Refactor Equality members

### ISSUE THREAD

**Issue by phmatray** [ivanpaulovich/clean-architecture-manga#92]
Hello, 

I have been discovering this great project for a few days now and I already wanted to thank you. :)

Would it be interesting to refactor the implementation of the IEquatable interface of value objects?

Here is a more concise implementation possibility used in ReSharper and Rider.

What do you think of that?

```csharp
namespace Domain.ValueObjects
{
    using System;
    
    public struct Name : IEquatable<Name>
    {
        private readonly string _text;

        public Name(string text)
        {
            if (string.IsNullOrWhiteSpace(text))
                throw new NameShouldNotBeEmptyException("The 'Name' field is required");
            
            _text = text;
        }

        public override string ToString()
            => _text;

        public bool Equals(Name other)
            => _text == other._text;

        public override bool Equals(object obj)
            => obj is Name other && Equals(other);

        public override int GetHashCode()
            => _text != null ? _text.GetHashCode() : 0;
    }
}
```

**Comment by ivanpaulovich** [comment]
Hey @phmatray!

Thanks for the feedback!

I think your proposed implementation is much clearer than the current one. Would you open a PR  including the other Value Types as well?

**Comment by phmatray** [comment]
Yes, of course, 
I'll take care of it tomorrow :)
Thank you.

**Comment by fals** [comment]
The equality will fail in case other is null. Null check is necessary in that case.

**Comment by ivanpaulovich** [comment]
Hey @fals! I suspect that as Name is a struct we don't need to check for null values.

**Comment by fals** [comment]
@ivanpaulovich indeed there's also a syntax check for it :), thought it was a class.

**Comment by ivanpaulovich** [comment]
@phmatray fixed it on https://github.com/ivanpaulovich/clean-architecture-manga/pull/97 🍺
