### ISSUE TITLE
Add support to Multiple Currencies

### ISSUE THREAD

**Issue by ivanpaulovich** [ivanpaulovich/clean-architecture-manga#98]
I would like to see support for multiple currencies. 

The challenge is that the current implementation uses a `Value Object` to describe Money in which there is no information regarding the Currency so it is not possible to deposit **Euros** and **Dollars**  to the same account history.

In the real world the customers deal seamlessly with multiple currencies and the bank is responsible for the exchange service.

How can we do the same in a DDD approach?

My first thought is to change the Money Value Object to  include info regarding the Original Currency and the Value in Euro then design a Factory object that is initialized with an `Exchange Service`.

After that we need to change the controllers to use the Factory instead of instantiating the `Money` directly.

Thoughts?

**Comment by vmamore** [comment]
Hey @ivanpaulovich,

I think this is pretty nice to do. I'm reading the TDD book by Kent Beck and in the first part he design the **Money** handling multiples currencies and the **Bank** that is what you call **Exchange Service**. I have one doubt, how would you implement to get the updated currencies values? Example: Today 1 Dollar could be 0.75 Euro, but tomorrow, 1 Dollar could be 1 Euro...

**Comment by ivanpaulovich** [comment]
Hi @vmamore,

The support for multiple currencies requires changes in the Domain, Persistence, Application, and WebApi. I suggest we first allow the WebApi to receive the currency name when executing the use cases.

For instance, the `Deposit` use case would allow the user to tell which currency he is using then internally the Money will be converted into a standard currency like EUR or USD.

1. Update the Request/Response to include currency name.
2. Update the Money value type.
3. Add ICurrencyExchange service.
4. Implement a fake currency exchange service.

**Comment by vmamore** [comment]
Hey @ivanpaulovich, how are you?

I made a PR to talk with you about some ideas, can you see it?

https://github.com/ivanpaulovich/clean-architecture-manga/pull/204

**Comment by ivanpaulovich** [comment]
Hi @vmamore,

Sorry. I am preparing a talk and I am a bit away from the project. 

I reviewed the design and added a few comments. Could you take a look?
 
Best

**Comment by vmamore** [comment]
Hey @ivanpaulovich,

No problem. I was trying to find the comments and I accidentally clicked in "ready to review".

I'm not finding the comments, can you indicate me where it is?

Thanks!

**Comment by ivanpaulovich** [comment]
Hi @vmamore, my bad. I didn't click on submit. Check if you got it now. Thanks!

**Comment by vmamore** [comment]
Hey @ivanpaulovich, how are you?

I made some changes and answered in the PR, can you validate?

Thanks!

**Comment by ivanpaulovich** [comment]
Included on https://github.com/ivanpaulovich/clean-architecture-manga/pull/220
